// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.27.3
// source: tgapi.proto

package tgapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TgServiceV1Client is the client API for TgServiceV1 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TgServiceV1Client interface {
	SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type tgServiceV1Client struct {
	cc grpc.ClientConnInterface
}

func NewTgServiceV1Client(cc grpc.ClientConnInterface) TgServiceV1Client {
	return &tgServiceV1Client{cc}
}

func (c *tgServiceV1Client) SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/tgapiv1.TgServiceV1/SendMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TgServiceV1Server is the server API for TgServiceV1 service.
// All implementations must embed UnimplementedTgServiceV1Server
// for forward compatibility
type TgServiceV1Server interface {
	SendMessage(context.Context, *SendMessageRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedTgServiceV1Server()
}

// UnimplementedTgServiceV1Server must be embedded to have forward compatible implementations.
type UnimplementedTgServiceV1Server struct {
}

func (UnimplementedTgServiceV1Server) SendMessage(context.Context, *SendMessageRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedTgServiceV1Server) mustEmbedUnimplementedTgServiceV1Server() {}

// UnsafeTgServiceV1Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TgServiceV1Server will
// result in compilation errors.
type UnsafeTgServiceV1Server interface {
	mustEmbedUnimplementedTgServiceV1Server()
}

func RegisterTgServiceV1Server(s grpc.ServiceRegistrar, srv TgServiceV1Server) {
	s.RegisterService(&TgServiceV1_ServiceDesc, srv)
}

func _TgServiceV1_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TgServiceV1Server).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tgapiv1.TgServiceV1/SendMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TgServiceV1Server).SendMessage(ctx, req.(*SendMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TgServiceV1_ServiceDesc is the grpc.ServiceDesc for TgServiceV1 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TgServiceV1_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tgapiv1.TgServiceV1",
	HandlerType: (*TgServiceV1Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMessage",
			Handler:    _TgServiceV1_SendMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tgapi.proto",
}
